# Macro file for the test Detector messenger
/run/initialize

/control/verbose 2
/run/verbose 2
/tracking/verbose 0

/tracking/storeTrajectory 1

/control/saveHistory

/Runmodel/ModelChoose NaI

#点源输入
/gps/particle neutron

/gps/pos/type Point
# particle source postition
/gps/pos/centre 0 0 9.02 cm 

# particle direction
/gps/ang/type iso 

#能谱输入
/gps/ene/type Arb
/gps/hist/type arb
#能量/数量输入
#              	 E(MeV) Rel.yield
/gps/hist/point    0.45 0.00
/gps/hist/point    0.5 1.00
/gps/hist/point    0.55 0.00

/gps/hist/inter Spline
#/gps/hist/inter Lin

/run/beamOn 1000000

